# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://tiphaine.github.io
baseurl: /me/
title: Tiphaine Phe-Neau - Data Scientist, PhD
author: Tiphaine Phe-Neau
description: Projects, technical blog and resume
avatar: profile.png
email: tiphaine@phe-neau.com
github: tiphaine # username
twitter: datatiph
linkedin: pheneau
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
#disqus: username
#google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
